---
- name: Download and install Packer
  unarchive:
    src: '{{ okd_lab_packer_url }}'
    dest: /usr/local/bin
    mode: '0755'
    remote_src: yes

- name: Download and install Terraform
  unarchive:
    src: '{{ okd_lab_terraform_url }}'
    dest: /usr/local/bin
    mode: '0755'
    remote_src: yes

- name: Initialize Terraform workspace
  command: terraform init
  become_user: lab
  args:
    chdir: /home/lab

- name: Create plugin directory
  file:
    path: /home/lab/.terraform.d/plugins
    state: directory
    mode: '0755'
  become_user: lab

- name: Download and install Terraform KVM plugin
  unarchive:
    src: '{{ okd_lab_terraform_kvm_url }}'
    dest: /home/lab/.terraform.d/plugins
    mode: '0755'
    remote_src: yes
  become_user: lab
